### PR TITLE
Fabric 1.16.1

### PR DESCRIPTION
**Pull request by Bulldog83**
I've made few more changes. Fixed damage render time and animation. But I didn't check bars hidding depends by config.

### CODE REVIEW

**Comment by Bulldog83** [comment]
Hmm. Yesterday’s commit got here too.

**Comment by frodare** [comment]
Sorry, that is my bad.  I always squash merge for various reasons (a personal preference, I understand the cons).  You should be able to easily fix by making a backup branch, then soft reseting to upstream/master.

**Comment by Bulldog83** [comment]
But upstream/master is for different minecraft version. :)

**Comment by frodare** [comment]
LOL, yes that would be bad.  Habits die hard.  upstream/fabric-1.16.1

**Comment by Bulldog83** [comment]
Ok. I'll try to recreate pull request.

**Pull request closed without merging**
